# right_format = "$time"
# format = "$directory($fill)$time\n$character"
format = """
$all\
$fill\
$time\
$line_break\
$jobs\
$battery\
$container\
$shell\
$character"""

command_timeout = 1500

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
style = "cyan bold"
# truncate_to_repo = true
# truncation_length = 3 # parent directories to show; default is 3
# truncation_symbol = "…/"
read_only = " "
home_symbol = " ~"
fish_style_pwd_dir_length = 5

[fill]
symbol = ' '

[time]
disabled = false
format = ' at [$time]($style) '
style = 'cyan'
use_12hr = true
utc_time_offset = 'local'

[shell]
format = '[$indicator]($style)'
bash_indicator = 'bsh '
fish_indicator = ''
zsh_indicator = 'zsh '
powershell_indicator = 'ps '
unknown_indicator = '??? '
style = 'cyan bold'
disabled = false

# disabled

[git_status]
disabled = true

[package]
disabled = true

# contextual configs

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = " "

[meson]
symbol = "喝 "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "ﳒ "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[spack]
symbol = "🅢 "
